name: "Install"
description: "Install Cloud Custodian"
inputs:
  python-version:
    required: true
  uv-version:
    required: true
outputs:
  uv-version:
    description: "uv version"
    value: ${{ steps.echo-uv-version.outputs.uv-version }}

runs:
  using: "composite"
  steps:
    - name: Install uv
      uses: astral-sh/setup-uv@85856786d1ce8acfbcc2f13a5f3fbd6b938f9f41 # ratchet:astral-sh/setup-uv@v5
      with:
        version: ${{ inputs.uv-version }}
        enable-cache: true

    - name: Set up Python ${{ inputs.python-version }}
      uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c # ratchet:actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}

    - name: Set up cache
      uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # ratchet:actions/cache@v4
      id: cache
      with:
        path: .venv
        key: venv-${{ runner.os }}-${{ inputs.python-version }}-${{ hashFiles('uv.lock') }}

    - name: Update PATH
      shell: bash
      run: |
        if [[ "$OSTYPE" == "msys" ]]
        then
          echo "$PWD\.venv\Scripts" >> $GITHUB_PATH
          echo "VIRTUAL_ENV=$PWD\.venv" >> $GITHUB_ENV
        else
          echo "$PWD/.venv/bin" >> $GITHUB_PATH
          echo "VIRTUAL_ENV=$PWD/.venv" >> $GITHUB_ENV
        fi

    - name: Ensure cache is healthy
      if: steps.cache.outputs.cache-hit == 'true'
      id: cache_check
      shell: bash
      run: |
        if uv run --no-sync custodian version ; then
           echo "venv=success" >> $GITHUB_OUTPUT
           echo "Cache Green"
        else
           rm -rf .venv
           echo "venv==recreate" >> $GITHUB_OUTPUT
           echo "Cache Red"
        fi

    - name: Install
      if: steps.cache.outputs.cache-hit != 'true' || steps.cache_check.outputs.venv != 'success'
      shell: bash
      env:
        CHECK_VENV: ${{ steps.cache_check.outputs.venv }}
        CACHE_HIT: ${{ steps.cache.outputs.cache-hit }}
      run: |
        echo "check venv $CHECK_VENV"
        echo "cache hit $CACHE_HIT"
        if [ -d ".venv" ]; then
          mv .venv .venv-old
        fi
        make install

    - name: Output UV Version
      shell: bash
      id: echo-uv-version
      run: echo "uv-version=${{ inputs.uv-version }}" >> $GITHUB_OUTPUT

    - name: Build awscc data files
      shell: bash
      run: cd tools/c7n_awscc && python build.py


    - name: Save cache
      if: steps.cache.outputs.cache-hit == 'true' && steps.cache_check.outputs.venv == 'recreate'
      uses: actions/cache/save@0057852bfaa89a56745cba8c7296529d2fc39830 # ratchet:actions/cache@v4
      with:
        path: .venv
        key: venv-${{ runner.os }}-${{ inputs.python-version }}-${{ hashFiles('uv.lock') }}
